import './global.css';
import { AppHeader } from '@byndr/ui';

export const metadata = {
  title: 'Welcome to byndr',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppHeader></AppHeader>
        {children}
      </body>
    </html>
  );
}
